// <auto-generated />
using System;
using Formula1.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formula1.API.Migrations
{
    [DbContext(typeof(Formula1Context))]
    partial class Formula1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Formula1.API.Entities.TeamLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The location of Ferrari Racing Team",
                            Location = "Monza",
                            TeamsId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "The location of Mercedes Racing Team",
                            Location = "Nürburgring",
                            TeamsId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "The location of Red Bull Racing Team",
                            Location = "Zandvoort",
                            TeamsId = 3
                        });
                });

            modelBuilder.Entity("Formula1.API.Entities.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ferrari Racing Team",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mercedes Racing Team",
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Red Bull Racing Team",
                            Name = "Red Bull"
                        });
                });

            modelBuilder.Entity("Formula1.API.Models.TeamLocation.TeamLocationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamLocationDto");
                });

            modelBuilder.Entity("Formula1.API.Entities.TeamLocation", b =>
                {
                    b.HasOne("Formula1.API.Entities.Teams", "Teams")
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Formula1.API.Models.TeamLocation.TeamLocationDto", b =>
                {
                    b.HasOne("Formula1.API.Entities.Teams", null)
                        .WithMany("TeamLocations")
                        .HasForeignKey("TeamsId");
                });

            modelBuilder.Entity("Formula1.API.Entities.Teams", b =>
                {
                    b.Navigation("TeamLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
